// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Disquera.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Disquera.Modelos.Autor", b =>
                {
                    b.Property<int>("id_autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nacionalidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("id_autor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Disquera.Modelos.Cancion", b =>
                {
                    b.Property<int>("id_cancion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Autorid_autor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("reproducciones")
                        .HasColumnType("TEXT");

                    b.HasKey("id_cancion");

                    b.HasIndex("Autorid_autor");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("Disquera.Modelos.Cancion", b =>
                {
                    b.HasOne("Disquera.Modelos.Autor", "Autor")
                        .WithMany("Canciones")
                        .HasForeignKey("Autorid_autor");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Disquera.Modelos.Autor", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
